name: CI

on:
  workflow_call:

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        framework: [actioncable, actionmailbox, actionmailer, actionpack, actiontext, actionview, activejob, activemodel, activerecord, activestorage, activesupport]
    steps:
      - name: ${{ matrix.framework }}
        run: bundle exec rake test
