name: CI

on: [push, pull_request]

env:
  CI: true
  BUILDKITE: true
  RAILS_ENV: test
  RACK_ENV: test
  MYSQL_HOST: 127.0.0.1
  MYSQL_PORT: 3306
  REDIS_HOST: redis
  REDIS_PORT: 6379
  PGHOST: 127.0.0.1
  PGUSER: postgres
  PGPORT: 5432
  BUNDLE_DEPLOYMENT: false

jobs:
  actioncable:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        ruby: ["2.7", "3.0", "3.1", "3.2"]
        include:
          - ruby: head
            experimental: true
          - ruby: jruby
            experimental: true
          - ruby: jruby-head
            experimental: true
          - ruby: truffleruby
            experimental: true
          - ruby: truffleruby-head
            experimental: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/build.yml
        with:
          ruby: ${{ matrix.ruby }}
      - name: Action cable Test
        run: echo "Action cable"

  actionview:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        ruby: ["2.7", "3.0", "3.1", "3.2"]
        include:
          - ruby: head
            experimental: true
          - ruby: jruby
            experimental: true
          - ruby: jruby-head
            experimental: true
          - ruby: truffleruby
            experimental: true
          - ruby: truffleruby-head
            experimental: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        uses: ./.github/workflows/build.yml
        with:
          ruby: ${{ matrix.ruby }}
      - name: ActionView Test
        run: echo "Action view"
