name: Test reusable action

on: [push, pull_request]

jobs:
  actioncable:
    uses: ./.github/workflows/work.yml
  guides:
    uses: ./.github/workflows/work.yml
  actionview:
    uses: ./.github/workflows/work.yml
