name: Rails tests

on: [push, pull_request]

jobs:
  actioncable:
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        ruby: ["2.7", "3.0", "3.1", "3.2"]
        include:
          - ruby: head
            experimental: true
    uses: ./.github/workflows/build.yml
    with:
      ruby: ${{ matrix.ruby }}
      experimental: ${{ matrix.experimental }}
  guides:
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        ruby: ["2.7", "3.0", "3.1", "3.2"]
        include:
        - ruby: head
          experimental: true
    uses: ./.github/workflows/build.yml
    with:
      ruby: ${{ matrix.ruby }}
      experimental: ${{ matrix.experimental }}
  actionview:
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        ruby: ["2.7", "3.0", "3.1", "3.2"]
        include:
        - ruby: head
          experimental: true
    uses: ./.github/workflows/build.yml
    with:
      ruby: ${{ matrix.ruby }}
      experimental: ${{ matrix.experimental }}
