name: Rails tests

on: [push, pull_request]

jobs:
  build:
    name: Ruby ${{ matrix.ruby }}
    strategy:
      fail-fast: false
      matrix:
        experimental: [false]
        ruby: [2.7, 3.0, 3.1, 3.2]
        include:
          - { experimental: true, ruby: 'head' }
    uses: ./.github/workflows/build.yml
    with:
      ruby: ${{ matrix.ruby }}
      experimental: false

  test:
    name: ${{ matrix.framework }}
    runs-on: ubuntu-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        framework: [actionpack, activerecord, actionview, actionmailer, activesupport, activemodel, activestorage, railties]

    steps:
      - name: Run tests
        run: bundle exec rake test
      # ruby_3_0:
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     ruby: 3.0
  #     experimental: false
  # ruby_3_1:
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     ruby: 3.1
  #     experimental: false
  # ruby_3_2:
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     ruby: 3.2
  #     experimental: false
  # ruby_head:
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     ruby: head
  #     experimental: true
