name: Reusable

on:
  workflow_call:
    inputs:
      ruby:
        description: 'Ruby version'
        required: true
        default: '2.7'
        type: string

jobs:
  reusable_workflow_job:
    name: 'Reusable build action'
    runs-on: ubuntu-latest

    steps:
      - name: Run job 1
        run: echo "Hello ${{ inputs.ruby }}"
