name: Reusable

on:
  workflow_call:
    inputs:
      ruby:
        description: 'Ruby version'
        required: false
        default: '2.7'
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7", "3.0", "3.1", "3.2"]
    steps:
      - name: Run job 1
        run: echo "Hello ${{ matrix.ruby }}"
      - name: Run job 2
        run: echo "Hello ${{ matrix.ruby }}"
      - name: Run job 3
        run: echo "Hello ${{ matrix.ruby }}"
      - name: sleep
        run: sleep 10s
        shell: bash

